### ISSUE TITLE
Can not install adapter in v3.2

### ISSUE THREAD

**Issue by ZeroQool007** [SwedishChef1/ioBroker.bosesoundtouch#15]
`$ ./iobroker url "https://github.com/SwedishChef1/ioBroker.bosesoundtouch" --debug
install https://github.com/SwedishChef1/ioBroker.bosesoundtouch/tarball/master
ERROR: events.js:160      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:9001
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1277:14)
    at listen (net.js:1313:10)
    at net.js:1423:9
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

ERROR: process exited with code 1`

Have you got a solution, please?

thanks and great works

**Comment by SwedishChef1** [comment]
You can install it directly in ioBroker.admin. You have to change configuration to show all 'latest' adapters instead of 'default' ('stable'?). There is no need to install it from a user specified URL.

**Comment by Apollon77** [comment]
This error normally not happends often ... try again, I would close this isssue because more system related then adapter related

**Comment by SwedishChef1** [comment]
This error normally not happens often ... try again. 
Closed because more system related then adapter related
