### ISSUE TITLE
No nowPlaying informations

### ISSUE THREAD

**Issue by senger1985** [SwedishChef1/ioBroker.bosesoundtouch#17]
If I play music with the new Bose-Skill by Amazon Alexa, it shows me only the source "Alexa" and nothing more. No "Art", "Artest", etc.
I think it will to be the same problem like in the version 0.1.8 before?

**Comment by JoJ123** [comment]
You see different informations in the BOSE Soundtouch application or on the display of the speaker? I'm not 100% sure, if the information you request is available.

**Comment by senger1985** [comment]
If I start the music in the Soundtouch application it shows me only the source "Alexa", but if I start the music by voice comment, it shows me all the right informations.

I hope now you understand me.

**Comment by JoJ123** [comment]
Yes, I will look for it and try to reproduce.

**Comment by JoJ123** [comment]
I reproduced this issue, but the soundtouch system or maybe Alexa is not returning more informations over the api. At the moment this can't be solved

**Comment by senger1985** [comment]
Thanks for the test.
